// import Image from 'next/image'
// import Script from 'next/script'
// import * as fs from 'fs'
// useEffect(() => {
//   const url = "http://localhost:3000/api/blogs"
//   fetch(url)
//     .then((response) => response.json())
//     .then(data => {
//       setBlog(data)
//     });

// }, [])

{/* <Script strategy='lazyOnload'> strategy='lazyOnload' --- it is use for slow loading of page's javascript so our website is fast. Our html and css will load after out havy javascript load  </Script> */ }
// export async function getStaticProps(context) {
//   let data = await fs.promises.readdir('blogdata')
//   let allblogs = []
//   let myFileData;
//   for (let item = 0; item < data.length; item++) {
//     myFileData = await fs.promises.readFile(`blogdata/${data[item]}`, 'utf8')
//     allblogs.push(JSON.parse(myFileData))

//   }
//   return {
//     props: { allblogs }
//   }
// }

import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import Link from 'next/link'
const Home = (props) => {
  const [blog, setBlog] = useState(props.allBlogs)
  function createMarkup(c) {
    return { __html: c };

  }
  return (
    <div className={styles.body}>
      <style jsx>{`
      .para{
        margin-top:5px;
        font-size:20px;
        margin-left: 24px;

      }

      .blogItem{        
          margin-top: 50px;

      }
      `}</style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='keywords' content='next, huntingcoder blog, bloging, hunting coder' />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className={styles.main}>


        <div className="blogs">
          <h1 className={styles.title}>Hunting Coder</h1>

          <div className={styles.myimgraper}>
            <img className={styles.myimg} alt="img" src="/coder.jpg" width={237} height={158} />
            {/* <Image className={styles.myimg} alt="img" src="/coder.jpg" width={237} height={158} /> */}
          </div>
          <span className="para"><b> A blog for hunting coder by hunting coder.</b></span>

          {blog.map((element) => {
            return (
              <div key={element.slug} className="blogItem">
                <h3>{element.title}</h3>
                {blog && <div dangerouslySetInnerHTML={createMarkup(element.content.substring(0, 80))} />}
                {/* <p>{element.content.substring(0, 70)}...</p> */}
                <button className={styles.btn}><Link href={`/blogpost/${element.slug}`}> Read more</Link></button>
              </div>
            )
          })}
        </div>
      </main>


    </div>
  )
}


export async function getServerSideProps(context) {
  const url = "http://localhost:3000/api/blogs"

  const data = await fetch(url)
  let allBlogs = await data.json()
  return {
    props: { allBlogs }
  }
}

export default Home